NUM_CATEGORIES = 13

ONES, TWOS, THREES, FOURS, FIVES, SIXES = range(6)
THREE_KIND = 6
FOUR_KIND = 7
FULL_HOUSE = 8
SMALL_STRAIGHT = 9
LARGE_STRAIGHT = 10
CHANCE = 11
YAHTZEE = 12

FULL_HOUSE_POINTS = 25
SMALL_STRAIGHT_POINTS = 30
LARGE_STRAIGHT_POINTS = 40
YAHTZEE_POINTS = 50

UPPER_BONUS_THRESHOLD = 63
UPPER_BONUS = 35
EXTRA_YAHTZEE_BONUS = 100