NUM_CATEGORIES = 13

ONES, TWOS, THREES, FOURS, FIVES, SIXES = range(1, 7)
THREE_KIND = 7
FOUR_KIND = 8
FULL_HOUSE = 9
SMALL_STRAIGHT = 10
LARGE_STRAIGHT = 11
CHANCE = 12
YAHTZEE = 13

FULL_HOUSE_POINTS = 25
SMALL_STRAIGHT_POINTS = 30
LARGE_STRAIGHT_POINTS = 40
YAHTZEE_POINTS = 50

UPPER_BONUS_THRESHOLD = 63
UPPER_BONUS = 35
EXTRA_YAHTZEE_BONUS = 100